### ISSUE TITLE
Does Number box check Number is entered?

### ISSUE THREAD

**Issue by Kise07** [Kise07/expense-trackerjs#1]
## Checking is entered is number or not.
<img width="415" alt="Screenshot 2023-10-28 at 5 33 25 PM" src="https://github.com/Kise07/expense-trackerjs/assets/73417521/d13f31d7-1a76-4ae7-961b-8988d68d2b54">

**Comment by chiku011** [comment]
hii i will do it can you assign this issue to me

**Comment by chiku011** [comment]
otherwise plz create new issue and assign it me

**Comment by ankitkumar0622** [comment]
Hi @Kise07 , can you please assign this task to me.

**Comment by Kise07** [comment]
# Please see the Issues and raise PR.
